server:
  port: 8080

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      mvc:
        routes:
          # ✅ Ruta de prueba externa (para comprobar altiro que enruta)
          - id: httpbin-test
            uri: https://httpbin.org
            predicates:
              - Path=/httpbin/**
            filters:
              - StripPrefix=1

          # ✅ EJEMPLO ruta a microservicio por Eureka (cuando lo tengas)
          # Cambia "users-service" por el nombre exacto que aparece en Eureka
          - id: users-service
            uri: lb://users-service
            predicates:
              - Path=/users/**
            filters:
              - StripPrefix=1

      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE

      globalcors:
        cors-configurations:
          "[/**]":
            allowedOriginPatterns: "*"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true