server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/dbtools
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
